# Generated by Django 5.1.4 on 2024-12-19 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='user',
        ),
        migrations.CreateModel(
            name='MobileTransactionHistory',
            fields=[
                ('basetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pay.basetransaction')),
                ('mobile_number', models.CharField(max_length=10)),
                ('plan', models.CharField(choices=[('199', 'Plan 1: ₹199 (1GB/day)'), ('399', 'Plan 2: ₹399 (2GB/day)'), ('599', 'Plan 3: ₹599 (3GB/day)')], max_length=10)),
            ],
            bases=('pay.basetransaction',),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('basetransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pay.basetransaction')),
                ('recipient', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI ID'), ('account', 'Account Number'), ('phone', 'Phone Number')], max_length=10)),
            ],
            bases=('pay.basetransaction',),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('Account_number', models.CharField(db_index=True, max_length=12, unique=True)),
                ('Phone_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('upi_id', models.CharField(db_index=True, max_length=15, unique=True)),
                ('Password', models.CharField(max_length=6)),
                ('Amount', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='basetransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.useraccount'),
        ),
        migrations.DeleteModel(
            name='Transaction_history',
        ),
        migrations.DeleteModel(
            name='User_account',
        ),
    ]
