# Generated by Django 5.1.4 on 2025-01-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_rename_mobiletransactionhistory_mobilerechargehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
