# Generated by Django 5.1.4 on 2025-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('identity', models.CharField(max_length=10)),
                ('payment_mode', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='privatetoken',
            name='token',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
