# Generated by Django 5.1.4 on 2025-01-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_savedata_alter_privatetoken_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedata',
            old_name='identity',
            new_name='IdentityOfUser',
        ),
        migrations.RenameField(
            model_name='savedata',
            old_name='token',
            new_name='PojectIdentity',
        ),
    ]
